orbs:
  docker: circleci/docker@1.7.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    resource_class: xlarge
    workflows:
  say-hello-workflow:
    jobs:
      - say-hello
parallelism: 3