jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    resource_class: Xlarge
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

parallelism: 5